repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: debug-statements
      - id: detect-private-key
      - id: no-commit-to-branch
        args:
          [
            "-b=develop",
            "-b=master",
          ]
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args:
        [
          "--force-single-line-imports",
          "--ensure-newline-before-comments",
          "--line-length=120",
        ]
